AWSTemplateFormatVersion: "2010-09-09"
Description: "Claims service (dev) on ECS Fargate behind ALB"

Parameters:
  ProjectName:
    Type: String
    Default: myapp
  Environment:
    Type: String
    Default: dev
  ContainerImage:
    Type: String
    Description: "ECR image URI for claims-service"
  ContainerPort:
    Type: Number
    Default: 8080
  DesiredCount:
    Type: Number
    Default: 1

Resources:
  # Security group for ECS tasks - allow traffic only from ALB SG on app port
  ClaimsServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${Environment}-claims-svc-sg"
      VpcId: !ImportValue
        Fn::Sub: "${ProjectName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: "${ProjectName}-${Environment}-AlbSecurityGroupId"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-claims-svc-sg"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Target group for the service
  ClaimsServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue
        Fn::Sub: "${ProjectName}-VpcId"
      Name: !Sub "${ProjectName}-${Environment}-claims-tg"
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: "/health"
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: "200"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 15
      HealthCheckTimeoutSeconds: 5

  # Listener rule for /claims* paths
  ClaimsServiceListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-AlbListenerHttpArn"
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - "/claims*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ClaimsServiceTargetGroup

  # Task definition for claims service
  ClaimsServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectName}-${Environment}-claims-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-EcsExecutionRoleArn"
      TaskRoleArn: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-EcsTaskRoleArn"
      ContainerDefinitions:
        - Name: "claims-service"
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: "${ProjectName}-${Environment}-EcsAppLogGroupName"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "claims-service"

  # ECS Service
  ClaimsService:
    Type: AWS::ECS::Service
    DependsOn:
      - ClaimsServiceListenerRule
    Properties:
      ServiceName: !Sub "${ProjectName}-${Environment}-claims-service"
      Cluster: !ImportValue
        Fn::Sub: "${ProjectName}-${Environment}-EcsClusterName"
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue
              Fn::Sub: "${ProjectName}-PrivateSubnet1Id"
            - !ImportValue
              Fn::Sub: "${ProjectName}-PrivateSubnet2Id"
          SecurityGroups:
            - !Ref ClaimsServiceSecurityGroup
      LoadBalancers:
        - ContainerName: "claims-service"
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref ClaimsServiceTargetGroup

Outputs:
  ClaimsServiceName:
    Description: "Name of the ECS service"
    Value: !Ref ClaimsService

  ClaimsServiceTargetGroupArn:
    Description: "Target group ARN for the claims service"
    Value: !Ref ClaimsServiceTargetGroup
