AWSTemplateFormatVersion: "2010-09-09"
Description: "Claims service ECS Fargate deployment for dev environment"

Parameters:
  ProjectName:
    Type: String
    Default: myapp
  Environment:
    Type: String
    Default: dev
  ContainerImage:
    Type: String
    Description: "Full ECR image URI with tag for claims-service"
  DesiredCount:
    Type: Number
    Default: 1

Resources:
  # Security group for ECS tasks - allow HTTP from within VPC CIDR
  ClaimsServiceTaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${Environment}-claims-tasks-sg"
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-VpcId"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 10.0.0.0/16   # allow ALB and other resources in VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: claims

  # Target group for claims-service
  ClaimsServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-claims-tg"
      Protocol: HTTP
      Port: 8080
      TargetType: ip
      VpcId:
        Fn::ImportValue: !Sub "${ProjectName}-VpcId"
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: "200-399"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: claims

  # Listener rule on dev ALB: /claims* -> this target group
  ClaimsServiceListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-AlbListenerHttpArn"
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - "/claims*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ClaimsServiceTargetGroup

  ClaimsServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectName}-${Environment}-claims-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-EcsExecutionRoleArn"
      TaskRoleArn:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-EcsTaskRoleArn"
      ContainerDefinitions:
        - Name: claims-service
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 8080
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub "${ProjectName}-${Environment}-EcsAppLogGroupName"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "claims"

  ClaimsServiceEcsService:
    Type: AWS::ECS::Service
    DependsOn:
      - ClaimsServiceListenerRule
    Properties:
      ServiceName: !Sub "${ProjectName}-${Environment}-claims-service"
      Cluster:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-EcsClusterName"
      LaunchType: FARGATE
      PlatformVersion: "LATEST"
      DesiredCount: !Ref DesiredCount
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ClaimsServiceTaskSecurityGroup
          Subnets:
            - Fn::ImportValue: !Sub "${ProjectName}-PrivateSubnet1Id"
            - Fn::ImportValue: !Sub "${ProjectName}-PrivateSubnet2Id"
      LoadBalancers:
        - ContainerName: claims-service
          ContainerPort: 8080
          TargetGroupArn: !Ref ClaimsServiceTargetGroup
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: claims

Outputs:
  ClaimsServiceName:
    Description: "Name of the ECS service"
    Value: !Ref ClaimsServiceEcsService
