AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Blue/Green Platform - FROM SCRATCH (StateFarm style)"

Parameters:
  ProjectName:
    Type: String
    Default: real-time-ecs-platform

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc"

