AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS base stack: execution role, task role, and app log group"

Parameters:
  ProjectName:
    Type: String
    Default: myapp
  Environment:
    Type: String
    Default: dev

Resources:
  # Role that ECS tasks use to pull images from ECR and send logs to CloudWatch
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-ecs-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Role that your application code can assume to access other AWS services (S3, SQS, etc.)
  # For now it has no permissions; we can add later per service.
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Environment}-ecs-task-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Logs group for ECS application logs in this environment
  ECSAppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}/${Environment}"
      RetentionInDays: 14

Outputs:
  ECSTaskExecutionRoleArn:
    Description: "ECS task execution role ARN"
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EcsExecutionRoleArn"

  ECSTaskRoleArn:
    Description: "ECS task role ARN"
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EcsTaskRoleArn"

  ECSAppLogGroupName:
    Description: "CloudWatch Logs group for ECS app logs"
    Value: !Ref ECSAppLogGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EcsAppLogGroupName"
